test:
  name: healthlocker-contract-benchmark
  description: A test benchmark
  workers:
    type: remote
    number: 10
  rounds:
    - label: Create Appointment
      description: This test will create appointments object
      txDuration: 3000
      rateControl:
          type: fixed-load
          opts:
            tps: 200
      workload:
        module: workload/invoke.js
        arguments:
          contractId: healthlocker
          contractFunction: createAppointment
    - label: Query All the Appointments
      description: Fetch all the stored Appointments
      txNumber: 1000
      rateControl:
         { type: "linear-rate", opts: { startingTps: 100, finishingTps: 450 } }
      workload:
         module: workload/read.js
         arguments:
           contractId: healthlocker
           contractFunction: queryAppointment
