certificateAuthorities:
  ord-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIQS4NZtSTir0gJ/DABhSzjNjAKBggqhkjOPQQDAjBSMRMw
        EQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQHEwAxCTAHBgNVBAkTADEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzAeFw0yNDA1MjYxMjQzMzZa
        Fw0zNDA1MjcxMjQzMzZaMFIxEzARBgNVBAYTCkNhbGlmb3JuaWExCTAHBgNVBAcT
        ADEJMAcGA1UECRMAMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFi
        cmljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1TvUax/jp4DN6bWOkvjCzx8s
        5Op4sscVJSfBGvve7lNofbx1TnlN1CCGPfVTWb3FUm3a4Xb7LBT1Ean4sYyQh6OB
        tTCBsjAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF
        BwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEICOLFgWfRuJuo5uGMprLZlX0
        fzWDLTb0avt7pjAjQi5IMEUGA1UdEQQ+MDyCCWxvY2FsaG9zdIIGb3JkLWNhgg1v
        cmQtY2EuZmFicmljghJvcmQtY2EucGxlbm9tZS5jb22HBH8AAAEwCgYIKoZIzj0E
        AwIDSAAwRQIgR7YfQnBrnoDgWHNpNEVWO3k5ylEPxVizPJvETK1+zJMCIQDIK1Gp
        AqH6ItYPoQJ5fudwzky9BAktQfNABZ/kKCOFNg==
        -----END CERTIFICATE-----
    url: https://ord-ca.plenome.com:443
  org1-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICXDCCAgKgAwIBAgIRAP4dV2Ci+UlLmRQNhHZ+KoUwCgYIKoZIzj0EAwIwUjET
        MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
        BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjQwNTI2MTI0MzI5
        WhcNMzQwNTI3MTI0MzI5WjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
        EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
        YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGXritC/ZhF6hEdvu4tadCdb
        TuZ5hX0QMsoMe090KNLQkLs3P+oKfiw09Kg+Fuf7dS0zRwd2W/aQMD9yZ5bGoKCj
        gbgwgbUwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
        BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAIGBau+SRcMp3/wuMyUleV
        sFH3vNKfGga2MRoqBY98+zBIBgNVHREEQTA/gglsb2NhbGhvc3SCB29yZzEtY2GC
        Dm9yZzEtY2EuZmFicmljghNvcmcxLWNhLnBsZW5vbWUuY29thwR/AAABMAoGCCqG
        SM49BAMCA0gAMEUCIQDVUCd7nx7Vnr4acP2Gy9uCBlYpbOYG4X6x+MQLclGvqAIg
        VoNRKpTacCdHaVZ/oJOiZtGq8ylTasszmxVGdS7Y9f0=
        -----END CERTIFICATE-----
    url: https://org1-ca.plenome.com:443
  org2-ca.fabric:
    caName: ca
    registrar:
      enrollId: enroll
      enrollSecret: enrollpw
    tlsCACerts:
      pem:
      - |
        -----BEGIN CERTIFICATE-----
        MIICWzCCAgGgAwIBAgIQEkQA/Q8TdcwdfSJCIGxXpTAKBggqhkjOPQQDAjBSMRMw
        EQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQHEwAxCTAHBgNVBAkTADEUMBIGA1UE
        ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzAeFw0yNDA1MjYxMjQzMzBa
        Fw0zNDA1MjcxMjQzMzBaMFIxEzARBgNVBAYTCkNhbGlmb3JuaWExCTAHBgNVBAcT
        ADEJMAcGA1UECRMAMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFi
        cmljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEa/ymVAXU1z9s4sIlRgfZ9Vdk
        EON4N1nkd8aZkunGo2Fqy25hE7zywLIdpybcuwzJx502YSwVxDIE48jZZm7LZKOB
        uDCBtTAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF
        BwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEINHXJRhDXlnvvXpn8ewjncof
        SSDjjeCHTFtCKJ6ZeHhZMEgGA1UdEQRBMD+CCWxvY2FsaG9zdIIHb3JnMi1jYYIO
        b3JnMi1jYS5mYWJyaWOCE29yZzItY2EucGxlbm9tZS5jb22HBH8AAAEwCgYIKoZI
        zj0EAwIDSAAwRQIhAKO36VQx0vrzPM4h6+lCCaIxftpXokYBgR7+ZtPDbN+sAiB6
        KdwAQHcWvScG8cJRlQkz1yBdTJYp/R9u+bfx005n3w==
        -----END CERTIFICATE-----
    url: https://org2-ca.plenome.com:443
channels:
  mychannel:
    orderers:
    - ord-node1.fabric
    - ord-node2.fabric
    - ord-node3.fabric
    peers:
      org1-peer1.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org1-peer2.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org2-peer1.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      org2-peer2.fabric:
        chaincodeQuery: true
        discover: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
client:
  organization: <no value>
name: hlf-network
orderers:
  ord-node1.fabric:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRzCCAeygAwIBAgIRAPXb/o585CD6mwDPB3QdRt0wCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjQwNTI2MTI0MzM2WhcNMzQwNTI3MTI0MzM2WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHd/cgOs/PwpCLtm
        gYfWHM36BnVZY3pkA7a6z3nNckZUYZg0xfLs4nNCemkn5TGt1MiM6NVpNXOBrI9Q
        odbtZACjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgtqo6tStzDb8JlAI0
        NFr2nsXlJlPZDoiMFkKfEq0Ex30wCgYIKoZIzj0EAwIDSQAwRgIhAOiaiuEOfsDS
        wmEQ7yy5k4FXbpbWn8gGjFkxExSk+6+vAiEAk8f0oRtMr6zhN565FEGoK7a23HMb
        zO3sI5HCgf/UGh0=
        -----END CERTIFICATE-----
    url: grpcs://orderer1-ord.plenome.com:443
  ord-node2.fabric:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRzCCAeygAwIBAgIRAPXb/o585CD6mwDPB3QdRt0wCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjQwNTI2MTI0MzM2WhcNMzQwNTI3MTI0MzM2WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHd/cgOs/PwpCLtm
        gYfWHM36BnVZY3pkA7a6z3nNckZUYZg0xfLs4nNCemkn5TGt1MiM6NVpNXOBrI9Q
        odbtZACjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgtqo6tStzDb8JlAI0
        NFr2nsXlJlPZDoiMFkKfEq0Ex30wCgYIKoZIzj0EAwIDSQAwRgIhAOiaiuEOfsDS
        wmEQ7yy5k4FXbpbWn8gGjFkxExSk+6+vAiEAk8f0oRtMr6zhN565FEGoK7a23HMb
        zO3sI5HCgf/UGh0=
        -----END CERTIFICATE-----
    url: grpcs://orderer2-ord.plenome.com:443
  ord-node3.fabric:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRzCCAeygAwIBAgIRAPXb/o585CD6mwDPB3QdRt0wCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjQwNTI2MTI0MzM2WhcNMzQwNTI3MTI0MzM2WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHd/cgOs/PwpCLtm
        gYfWHM36BnVZY3pkA7a6z3nNckZUYZg0xfLs4nNCemkn5TGt1MiM6NVpNXOBrI9Q
        odbtZACjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgtqo6tStzDb8JlAI0
        NFr2nsXlJlPZDoiMFkKfEq0Ex30wCgYIKoZIzj0EAwIDSQAwRgIhAOiaiuEOfsDS
        wmEQ7yy5k4FXbpbWn8gGjFkxExSk+6+vAiEAk8f0oRtMr6zhN565FEGoK7a23HMb
        zO3sI5HCgf/UGh0=
        -----END CERTIFICATE-----
    url: grpcs://orderer3-ord.plenome.com:443
organizations:
  OrdererMSP:
    cryptoPath: /tmp/cryptopath
    mspid: OrdererMSP
    orderers:
    - ord-node1.fabric
    - ord-node2.fabric
    - ord-node3.fabric
    peers: []
    users: {}
  Org1MSP:
    cryptoPath: /tmp/cryptopath
    mspid: Org1MSP
    orderers: []
    peers:
    - org1-peer1.fabric
    - org1-peer2.fabric
    users:
      admin:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAfmgAwIBAgIULaS6xwaZySog1TYYtBSu0w3H7NwwCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjQwNTI2MTI0MzI5WhcNMjUwNTI3MTI1NDAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAAQJP6mVf4avCXf9fLviQbfN+0Lz/wbxASGFrGh/fGOBbsdKXpBE6aXJ
            +LxuyIJXokCwdZZFljOjLKLW+IXryVbUo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQOxUvWFOXGoon7p42qOjDtHDIrNTArBgNV
            HSMEJDAigCBpLGEbQjuWHYIXp9Q4N9YTyyC+/9QhzB4tBt11eDquujBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0cA
            MEQCIF8XxS2eg2O9dM6Ta6z+7lcB7vuYwi53hOZU3vkiu8BzAiBT5/rcYHdpfNCP
            g1JtWEq8F2c7Tg8a+QWrf7jfCWIRpg==
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgFk5CaCjVT0U23yFq
            qXabm37457YVKv5IIlasBzH/KqGhRANCAAQJP6mVf4avCXf9fLviQbfN+0Lz/wbx
            ASGFrGh/fGOBbsdKXpBE6aXJ+LxuyIJXokCwdZZFljOjLKLW+IXryVbU
            -----END PRIVATE KEY-----
  Org2MSP:
    cryptoPath: /tmp/cryptopath
    mspid: Org2MSP
    orderers: []
    peers:
    - org2-peer1.fabric
    - org2-peer2.fabric
    users:
      admin:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUzCCAfmgAwIBAgIUZqLG2zWBDnxewEUMo6+PCvMEuYgwCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjQwNTI2MTI0MzMwWhcNMjUwNTI3MTI1NDAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAATElKGWecJG+WRRc67Gn2PGVgZ3DEX1HctTcMNuMiHcJpq0gEJHzfCB
            oqv66cNkbtVRCyWMaiGPzWU1v6vtQuv7o4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTMcqDUTQ35Doeb2ZzyrtVOfmEkQDArBgNV
            HSMEJDAigCD1y2UEedoNEz7uAQxc3z2Fk3MySmbB+pRmIfrkGiqvIDBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0gA
            MEUCIQCkhfpc/QBtXWi8FL1u4o2H2vFCHmSsbfWMRoJa69M1NQIgDXbPWqqVrDg0
            q5p6HOpieYsTGzabhiwrE22Zxgnm5/Y=
            -----END CERTIFICATE-----
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg4g5Vly0NBD1bvTKL
            VGX2P5m+z8QWOmp9pTApq+iWQXChRANCAATElKGWecJG+WRRc67Gn2PGVgZ3DEX1
            HctTcMNuMiHcJpq0gEJHzfCBoqv66cNkbtVRCyWMaiGPzWU1v6vtQuv7
            -----END PRIVATE KEY-----
peers:
  org1-peer1.fabric:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQJogmeUFHBsldxnRV0v6XgjAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNDA1MjYxMjQzMjlaFw0zNDA1MjcxMjQzMjlaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAErP0LIhDlBrCFSWEA
        8oMl/4l303KGStejFtB10CVFu8mKhgZgCE3vnkRImkh14IMjViYrm65Vr5fgHWtW
        QAIpuaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAaSy7MDNMGRNNHTJLu
        eTSt3TWduxYCBmd8TJFQFEEPKjAKBggqhkjOPQQDAgNJADBGAiEAjV29cpwx1NWE
        h+IQO+odp9tUw8Ge6Csp3VsR0jgl5MoCIQCn+9GYQiF9QDG+KYzsfMIO22lljM1F
        KU6j+iHaWwdUmQ==
        -----END CERTIFICATE-----
    url: grpcs://peer1-org1.plenome.com:443
  org1-peer2.fabric:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQJogmeUFHBsldxnRV0v6XgjAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNDA1MjYxMjQzMjlaFw0zNDA1MjcxMjQzMjlaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAErP0LIhDlBrCFSWEA
        8oMl/4l303KGStejFtB10CVFu8mKhgZgCE3vnkRImkh14IMjViYrm65Vr5fgHWtW
        QAIpuaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAaSy7MDNMGRNNHTJLu
        eTSt3TWduxYCBmd8TJFQFEEPKjAKBggqhkjOPQQDAgNJADBGAiEAjV29cpwx1NWE
        h+IQO+odp9tUw8Ge6Csp3VsR0jgl5MoCIQCn+9GYQiF9QDG+KYzsfMIO22lljM1F
        KU6j+iHaWwdUmQ==
        -----END CERTIFICATE-----
    url: grpcs://peer2-org1.plenome.com:443
  org2-peer1.fabric:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRTCCAeugAwIBAgIQAOOlUT7YdIZmqjcLpbrTtzAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNDA1MjYxMjQzMzBaFw0zNDA1MjcxMjQzMzBaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEN84V3F0/x1dy8gp9
        eRPaipytl1q4Hhb7F+cSm3RqGEvMFDF3kF4Jug28PeNs08Vvt7FK5xpqfzVwCkdJ
        5sOHs6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCAeoE5hGEup9LLf/qy
        Z0X7Njtjc4sgfiqf3Xbn9dUWATAKBggqhkjOPQQDAgNIADBFAiEAqXK+rju2+RaA
        4Eqr17X1CnRt7i2L0Qnt2mKW6Xp5Y6wCIDAmjcadLaWvx/pezAykHEVe8QgUaZTx
        6eTFmvpoPheH
        -----END CERTIFICATE-----
    url: grpcs://peer1-org2.plenome.com:443
  org2-peer2.fabric:
    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRTCCAeugAwIBAgIQAOOlUT7YdIZmqjcLpbrTtzAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNDA1MjYxMjQzMzBaFw0zNDA1MjcxMjQzMzBaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEN84V3F0/x1dy8gp9
        eRPaipytl1q4Hhb7F+cSm3RqGEvMFDF3kF4Jug28PeNs08Vvt7FK5xpqfzVwCkdJ
        5sOHs6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCAeoE5hGEup9LLf/qy
        Z0X7Njtjc4sgfiqf3Xbn9dUWATAKBggqhkjOPQQDAgNIADBFAiEAqXK+rju2+RaA
        4Eqr17X1CnRt7i2L0Qnt2mKW6Xp5Y6wCIDAmjcadLaWvx/pezAykHEVe8QgUaZTx
        6eTFmvpoPheH
        -----END CERTIFICATE-----
    url: grpcs://peer2-org2.plenome.com:443
version: 1.0.0
